Repository hibit-team/hibit-frontend, pull requests merged in 2023-10, with the labels that each got.

#52 Footer 매뉴얼, 이용약관 CTA 추가
  src/api/LoginAPI.ts
  src/components/Common/Footer/intex.tsx
  src/components/Common/Header/index.tsx
  src/components/Login/GoogleRedirectHandler/index.tsx
  src/components/Main/MatchIntros/index.tsx
  src/components/Main/MatchIntros/styles.ts
  src/hooks/useLoginInfo.tsx
  src/pages/MyProfile/PostMyProfile/index.tsx
  src/services/HttpClient.ts
Labels: 기능 추가

#53 로그인 상태관리
  src/api/LoginAPI.ts
  src/components/Common/Header/index.tsx
  src/hooks/useLoginInfo.tsx
  src/pages/MyProfile/PostMyProfile/index.tsx
  src/pages/MyProfile/PutMyProfile/index.tsx
  src/pages/OtherProfile/index.tsx
  src/pages/Posting/PostPosting/index.tsx
  src/recoil/atom/AlarmCount.ts
  src/recoil/atom/LoginInfoState.ts
Labels: 리팩토링

#55 Feat/qa 로그인상태값 및 모달 로직 수정
  src/components/GlobalModal/index.tsx
  src/components/MatchPost/PostReplySection/index.tsx
  src/components/Matching/FilterButton/index.tsx
Labels: 리팩토링

#56 Fix: 로그인 로직 수정
  src/api/LoginAPI.ts
  src/components/Common/Footer/intex.tsx
  src/components/Common/Header/index.tsx
  src/components/GlobalModal/index.tsx
  src/components/Login/GoogleRedirectHandler/index.tsx
  src/components/Main/MatchIntros/index.tsx
  src/components/Main/MatchIntros/styles.ts
  src/components/MatchPost/PostReplySection/index.tsx
  src/components/Matching/FilterButton/index.tsx
  src/hooks/useLoginInfo.tsx
  src/pages/MyProfile/PostMyProfile/index.tsx
  src/pages/MyProfile/PutMyProfile/index.tsx
  src/pages/OtherProfile/index.tsx
  src/pages/Posting/PostPosting/index.tsx
  src/recoil/atom/AlarmCount.ts
  src/recoil/atom/LoginInfoState.ts
  src/services/HttpClient.ts
Labels: 버그 수정

#57 feat: 로그인 해결
  src/App.tsx
  src/components/GlobalModal/index.tsx
  src/hooks/useLoginInfo.tsx
  src/recoil/atom/LoginInfoState.ts
Labels: 버그 수정

#58 refactor/QA 전 로그인 수정
  src/components/Alarm/index.tsx
  src/components/Common/Header/index.tsx
  src/components/GlobalModal/index.tsx
  src/components/Login/GoogleRedirectHandler/index.tsx
  src/components/MatchPost/PostLabel/index.tsx
  src/components/MatchPost/PostReplySection/index.tsx
  src/components/Matching/FilterButton/index.tsx
  src/components/Matching/SearchBar/index.tsx
  src/components/Matching/SearchBar/styles.ts
  src/hooks/useLoginInfo.tsx
  src/pages/Main/index.tsx
  src/pages/MatchPost/index.tsx
  src/pages/MyProfile/PostMyProfile/index.tsx
  src/pages/MyProfile/PutMyProfile/index.tsx
  src/pages/OtherProfile/index.tsx
  src/recoil/atom/LoginInfoState.ts
Labels: 버그 수정

#63 Feat/ 알림 초대장 수락, 거절 이후 UI
  src/components/Alarm/Invitation/index.tsx
Labels: 디자인

#64 feat: 알림 CTA 디자인 수정
  src/components/Alarm/Invitation/index.tsx
  src/components/Alarm/Invitation/styles.ts
Labels: 디자인

#68 QA: 신고하기, 리디렉션 에러 및 기타 수정
  src/components/MatchPost/PostArticle/index.tsx
  src/components/MatchPost/ReportModal/index.tsx
  src/components/Matching/SearchBar/index.tsx
  src/hooks/MatchingPost/usePostReport.ts
  src/pages/MatchPost/index.tsx
  src/pages/Posting/PutPosting/index.tsx
Labels: 버그 수정

#69 Refactor/ 신고하기, 리다이렉션 수정
  src/components/MatchPost/PostArticle/index.tsx
  src/components/MatchPost/ReportModal/index.tsx
  src/components/Matching/SearchBar/index.tsx
  src/hooks/MatchingPost/usePostReport.ts
  src/pages/MatchPost/index.tsx
  src/pages/Posting/PutPosting/index.tsx
Labels: 리팩토링

#73 Styles/ 구글 로그인 버튼 가운데 정렬
  src/components/Login/LoginModal/styles.ts
  src/components/OtherProfile/ImageCarousel/index.tsx
  src/pages/MyProfile/PutMyProfile/index.tsx
  src/pages/OtherProfile/index.tsx
  src/pages/OtherProfile/styles.ts
Labels: 리팩토링, 기능 추가, 디자인, 버그 수정

#74 Refactor/ 오픈채팅방 링크 이동 수정
  src/components/Alarm/Openchat/index.tsx
  src/pages/MyProfile/PutMyProfile/index.tsx
Labels: 리팩토링
