Repository hibit-team/hibit-frontend, pull requests merged in 2023-09, with the labels that each got.

#44 게시글 내부페이지 및 잔여 세부작업 진행 완료
  src/App.tsx
  src/components/Common/Header/index.tsx
  src/components/Common/Header/styles.ts
  src/components/GlobalModal/index.tsx
  src/components/Main/MainTab/styles.ts
  src/components/Main/MatchIntros/styles.ts
  src/components/Main/TabImgs/index.tsx
  src/components/Main/TabImgs/styles.ts
  src/components/MatchPost/PostArticle/index.tsx
  src/components/MatchPost/PostLabel/index.tsx
  src/components/MatchPost/PostReplySection/index.tsx
  src/components/Matching/FilterButton/index.tsx
  src/components/Matching/FilterButton/styles.ts
  src/components/Matching/MatchingContainer/styles.ts
  src/components/Matching/SearchBar/index.tsx
  src/components/Matching/SearchBar/styles.ts
  src/components/Matching/SlideBanner/index.tsx
  src/components/Matching/SlideBanner/styles.ts
  src/hooks/MatchingPost/usePostCompleteUserList.ts
  src/images/components/Arrow.svg
  src/images/components/HibitLogoWhite.svg
  src/images/components/Main/helloSmile.png
  src/images/components/Main/mainLeft.svg
  src/images/components/Main/mainRight.svg
  src/images/components/Main/nowTogoButton.svg
  src/images/components/Matching/banner.svg
  src/images/components/Purple.svg
  src/images/components/TwoPeople 오후 4.07.10.svg
  src/images/components/people.svg
  src/images/components/purplebg.svg
  src/images/components/swimmer.svg
  src/pages/Main/index.tsx
  src/pages/MatchPost/index.tsx
  src/pages/Matching/index.tsx
  src/pages/NotFound/index.tsx
  src/pages/NotFound/styles.ts
  src/pages/OtherProfile/index.tsx
  src/recoil/atom/GlobalModalOpenSwitch.ts
  src/recoil/atom/GlobalModalTextState.ts
  src/recoil/atom/LoginModalState.ts
Labels: 리팩토링, 기능 추가, 디자인

#45 로그인&로그아웃 / 본인 프로필 등록 및 수정 / 매칭게시글 등록 및 수정
  package-lock.json
  package.json
  src/App.tsx
  src/api/AlarmAPI.ts
  src/api/FileAPI.ts
  src/api/MyprofileAPI.ts
  src/api/OtherprofileAPI.ts
  src/api/PostingAPI.ts
  src/assets/data/personality/tmpPersonality.ts
  src/components/Alarm/index.tsx
  src/components/CalendarComponent/index.tsx
  src/components/Common/Header/index.tsx
  src/components/Login/GoogleRedirectHandler/index.tsx
  src/components/Login/LoginModal/index.tsx
  src/components/Matching/FilterButton/index.tsx
  src/components/PostingImage/index.tsx
  src/components/PostingImage/styles.ts
  src/components/ProfileImage/index.tsx
  src/components/ProfileImage/styles.ts
  src/hooks/useLoginInfo.tsx
  src/images/components/Posting/CloseDateBtn.svg
  src/index.tsx
  src/interfaces/IImage.ts
  src/interfaces/Posting/IDateFormat.ts
  src/interfaces/Posting/IPosting.ts
  src/interfaces/Profile/IProfile.ts
  src/interfaces/Profile/IimgProps.ts
  src/pages/Main/index.tsx
  src/pages/MyProfile/PostMyProfile/index.tsx
  src/pages/MyProfile/PostMyProfile/styles.ts
  src/pages/MyProfile/PutMyProfile/index.tsx
  src/pages/MyProfile/PutMyProfile/styles.ts
  src/pages/MyProfile/index.tsx
  src/pages/OtherProfile/index.tsx
  src/pages/Posting/PostPosting/index.tsx
  src/pages/Posting/PostPosting/styles.ts
  src/pages/Posting/PutPosting/index.tsx
  src/pages/Posting/PutPosting/styles.ts
  src/pages/Posting/index.tsx
  src/recoil/atom/AlarmCount.ts
  src/recoil/atom/LoginInfoState.ts
  src/services/HttpClient.ts
Labels: 리팩토링, 기능 추가, 디자인, 버그 수정

#46 게시글내부페이지 세부 추가 작업
  src/App.tsx
  src/components/Common/Header/index.tsx
  src/components/GlobalModal/index.tsx
  src/components/MatchPost/PostArticle/index.tsx
  src/components/MatchPost/PostReplySection/index.tsx
  src/components/MatchPost/PostReplySection/styles.ts
  src/components/Matching/FilterButton/index.tsx
  src/components/Matching/MatchingContainer/styles.ts
  src/hooks/MatchingPost/useDeleteMatchingPostMutation.ts
  src/hooks/MatchingPost/useDeleteReplyMutation.ts
  src/hooks/MatchingPost/useGetInviteModalList.ts
  src/hooks/MatchingPost/usePostMatchingArticleLikeMutation.ts
  src/hooks/MatchingPost/usePostReplyLikeMutation.ts
  src/hooks/MatchingPost/usePostSecondaryReplyInputMutation.ts
  src/hooks/MatchingPost/useUpdateReplyTextMutation.ts
  src/hooks/MatchingPost/useUpdateStateAndPostUserList.ts
  src/pages/Main/index.tsx
  src/pages/MatchPost/index.tsx
  src/pages/MobileLanding/index.tsx
  src/pages/MobileLanding/styles.ts
  src/pages/OtherProfile/index.tsx
Labels: 리팩토링

#47 otherprofile, 알림 CTA 반영
  src/api/MatchingAPI.ts
  src/api/OtherprofileAPI.ts
  src/api/PostingAPI.ts
  src/assets/data/alarm/tmpAlarmData.ts
  src/components/Alarm/Accept/index.tsx
  src/components/Alarm/Comment/index.tsx
  src/components/Alarm/CommentHeart/index.tsx
  src/components/Alarm/Invitation/index.tsx
  src/components/Alarm/Openchat/index.tsx
  src/components/Alarm/Recomment/index.tsx
  src/components/Alarm/Refuse/index.tsx
  src/components/Alarm/Remind/index.tsx
  src/interfaces/Alarm/IAlarm.ts
  src/pages/MyProfile/PostMyProfile/index.tsx
  src/pages/MyProfile/PutMyProfile/index.tsx
  src/pages/OtherProfile/index.tsx
  src/pages/OtherProfile/styles.ts
  src/pages/Posting/PostPosting/index.tsx
Labels: 리팩토링

#51 Footer 및 프로필 상세 텍스트 추가
  src/components/Common/Footer/intex.tsx
  src/components/Common/Footer/styles.ts
  src/images/components/Footer/arrowLogo.svg
  src/images/components/Footer/githubLogo.svg
  src/images/components/Footer/instagramLogo.svg
  src/pages/MyProfile/PostMyProfile/index.tsx
  src/pages/MyProfile/PostMyProfile/styles.ts
  src/pages/MyProfile/PutMyProfile/index.tsx
  src/pages/MyProfile/PutMyProfile/styles.ts
Labels: 기능 추가, 디자인
