Repository hibit-team/hibit-frontend, pull requests merged in 2023-07, with the labels that each got.

#24 refactor: 프로필 등록 페이지 이미지 추가 에러 해결
  src/pages/MyProfile/index.tsx
Labels: 리팩토링

#26 타인 프로필 조회 페이지
  package-lock.json
  package.json
  src/App.tsx
  src/components/OtherProfile/ImageCarousel/index.tsx
  src/components/OtherProfile/ImageCarousel/styles.ts
  src/images/components/OtherProfile/LockIcon.png
  src/images/components/OtherProfile/ZoomInIcon.svg
  src/pages/OtherProfile/index.tsx
  src/pages/OtherProfile/styles.ts
Labels: 기능 추가, 디자인

#28 Feat/match-component: 게시글 내부페이지UI 및 기본기능 추가 (rebased)
  .prettierrc
  package-lock.json
  package.json
  src/App.tsx
  src/assets/slick.css
  src/components/MatchPost/PostArticle/index.tsx
  src/components/MatchPost/PostArticle/styles.ts
  src/components/MatchPost/PostLabel/index.tsx
  src/components/MatchPost/PostLabel/styles.ts
  src/components/MatchPost/PostReplySection/index.tsx
  src/components/MatchPost/PostReplySection/styles.ts
  src/components/Matching/FilterButton/index.tsx
  src/components/Matching/MatchingContainer/index.tsx
  src/components/Matching/MatchingContainer/likeIcon.svg
  src/components/Matching/MatchingContainer/replyIcon.svg
  src/components/Matching/MatchingContainer/styles.ts
  src/components/Matching/SearchBar/index.tsx
  src/components/Matching/SlideBanner/index.tsx
  src/fonts/font.css
  src/images/components/MatchPost/ArrowDown.svg
  src/images/components/MatchPost/ArrowUp.svg
  src/images/components/MatchPost/ArticleArrow.webp
  src/images/components/MatchPost/EmptyRoundLike.png
  src/images/components/MatchPost/Tim.svg
  src/images/components/MatchPost/YellowRoundLike.svg
  src/images/components/MatchPost/emptyReplyArrow.svg
  src/images/components/MatchPost/pepe.jpeg
  src/images/components/MatchPost/profileDefault.svg
  src/images/components/MatchPost/purpleKebap.svg
  src/images/components/MatchPost/purpleLike.png
  src/images/components/MatchPost/replyArrow.svg
  src/images/components/MatchPost/whiteLike.png
  src/images/components/MatchPost/yellowLike.svg
  src/images/components/Swimmer 오후 4.07.10.svg
  src/images/components/swimmer 오후 4.24.34.svg
  src/pages/MatchPost/index.tsx
  src/pages/MatchPost/styles.ts
  src/pages/Matching/index.tsx
  src/pages/Matching/styles.ts
  src/recoil/atom/FsImageBoxToggler.ts
Labels: 기능 추가, 디자인

#30 게시글 작성 페이지 구현
  package-lock.json
  package.json
  src/App.tsx
  src/components/CalendarComponent/index.tsx
  src/components/CalendarComponent/styles.ts
  src/env
  src/images/components/Posting/AddBtn.svg
  src/images/components/Posting/AddCalendarIcon.svg
  src/images/components/Posting/AddCalendarIconGray.svg
  src/images/components/Posting/OpenchatGuide.svg
  src/pages/Posting/index.tsx
  src/pages/Posting/styles.ts
Labels: 기능 추가, 디자인

#31 게시글 등록 페이지 - date click 이벤트 처리 및 alert 로직 추가
  src/components/CalendarComponent/index.tsx
  src/pages/Posting/index.tsx
Labels: 기능 추가

#34 API template 작성
  src/api/CommentAPI.ts
  src/api/ExhibitionAPI.ts
  src/api/FileAPI.ts
  src/api/MatchingAPI.ts
  src/api/PostingAPI.ts
  src/services/HttpClient.ts
Labels: 기능 추가
